image: docker:latest
services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
- build
- package
- deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package"
  artifacts:
    paths:
    - target/*.jar

build:
  stage: package
  script:
  - docker build ./ -t pashket-bot

deploy:
  stage: deploy
  script:
  - docker run pashket-bot